### ISSUE TITLE
Cvars not working (at all)

### ISSUE THREAD

**Issue by deliriumbg** [Arkshine/AdminFreeLook#12]
Cvars aren't working currently:

amx_cvar afl_admin_access_flags
[AMXX] Unknown cvar: afl_admin_access_flags
amx_cvar amx_adminfreelookflag
[AMXX] Unknown cvar: amx_adminfreelookflag

Admin Free Look  RUN   -    adminfreelook_am  v1.5.5-p

**Comment by Arkshine** [comment]
Sorry for delay, did not see notifications.
They are working for me.

First should be working, second has been renamed.

From server console:

```
cvarlist afl
CVar List
--------------
afl_admin_access_flags :        0
afl_enabled     :        1, a
afl_user_override_mode :        0
--------------
```

From client console:

```
] amx_cvar afl_enabled
[AMXX] Cvar "afl_enabled" is "1"
] amx_cvar afl_admin_access_flags
[AMXX] Cvar "afl_admin_access_flags" is "d"
] amx_cvar afl_user_override_mode
[AMXX] Cvar "afl_user_override_mode" is "0"
```
