### ISSUE TITLE
Error in syslog when using maintance release 1.5.5

### ISSUE THREAD

**Issue by r4sas** [Arkshine/AdminFreeLook#13]
Hi, Arkshine!
When I using maintance release 1.5.5, I see that type of errors:

[52066.127242] hlds_linux[7769]: segfault at 80000 ip 00000000f76af966 sp 00000000ffff960c error 6 in localizebugfix_mm_i386.so[f76ae000+4000]

Using it, because have the same problem with auto changing view point to teammate after death.

mp_ cvars set to 1
amx_adminfreelookflag "c"
amx_adminfreelookmode "bd"

I really doesnt know, how it depends on AFL, but I have that error only when use 1.5.5 version.

**Comment by Arkshine** [comment]
Looking at your crash it happens in localizebugfix metamod module, not adminfreelook.

**Comment by r4sas** [comment]
Updated 1st message:
I really doesnt know, how it depends on AFL, but I have that error only when use 1.5.5 version.

Yeah, not only that...
hlds_linux[14494]: segfault at 0 ip 00000000f7660d26 sp 00000000ff90e7e0 error 4 in adminfreelook_amxx_i386.so[f765e000+4000]
hlds_linux[14532]: segfault at 0 ip 00000000f766dd26 sp 00000000ff9225b0 error 4 in adminfreelook_amxx_i386.so[f766b000+4000]
hlds_linux[14564]: segfault at 0 ip 00000000f76d4d26 sp 00000000ff8e4a20 error 4 in adminfreelook_amxx_i386.so[f76d2000+4000]
hlds_linux[14596]: segfault at 0 ip 00000000f76e8d26 sp 00000000ffc2bc80 error 4 in adminfreelook_amxx_i386.so[f76e6000+4000]

**Comment by Arkshine** [comment]
I don't know too.

localizebugfix hooks `Cmd_TokenizeString` and `ClientUserInfoChanged` from engine.
adminfreelooks hooks `CBasePlayer::Observer_IsValidTarget` and `Observer_SetMode` from mod.

They have no relations whether direct or indirect.

How do you reproduce crash exactly?

**Comment by Arkshine** [comment]
By the way, if you're using 1.5.5, cvars have been renamed.

**Comment by r4sas** [comment]
I'll try reproduce error again. Now I again installed 1.5.5 (after that errors replaced to 1.5.4), but module doesn't works.
amxx.cfg (executed, server restarted):
afl_enabled 1
afl_admin_access_flags "c"
afl_user_override_mode "bd"
amx_adminfreelookflag "c"
amx_adminfreelookmode "bd"

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] dproto_EF        RUN   -    dproto_i386.so    v0.9.534  ini  Start Never
 [ 2] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2.0RC1   ini  ANY   ANY
 [ 3] LocalizeBug Fix  RUN   -    localizebugfix_m  v2.4      ini  Start Never
 [ 4] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini  Start ANY
 [ 5] Semiclip         RUN   -    semiclip_mm_i386  v2.2      ini  ANY   ANY
 [ 6] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.623  ini  Chlvl ANY
 [ 7] Admin Free Look  RUN   -    adminfreelook_am  v1.5.5-p  pl4  ANY   ANY
 [ 8] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl4  ANY   ANY
 [ 9] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2    pl4  ANY   ANY
 [10] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl4  ANY   ANY
 [11] MySQL            RUN   -    mysql_amxx_i386.  v1.8.2    pl4  ANY   ANY
 [12] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.2    pl4  ANY   ANY
 [13] Engine           RUN   -    engine_amxx_i386  v1.8.2    pl4  ANY   ANY
 [14] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl4  ANY   ANY
 [15] Orpheu           RUN   -    orpheu_amxx_i386  v2.6.3    pl4  ANY   ANY
15 plugins, 15 running
Also I can't find afl_ cvars from 'meta cvars' output.

But on second server with AMXX 1.8.3 it works correctly:
meta list
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] dproto_EF        RUN   -    dproto_i386.so    v0.9.548  ini  Start Never
 [ 2] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2.0RC1   ini  ANY   ANY
 [ 3] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.620  ini  Chlvl ANY
 [ 4] LocalizeBug Fix  RUN   -    localizebugfix_m  v2.4      ini  Start Never
 [ 5] Semiclip         RUN   -    semiclip_mm_i386  v2.2      ini  ANY   ANY
 [ 6] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-d  ini  Start ANY
 [ 7] Admin Free Look  RUN   -    adminfreelook_am  v1.5.5-p  pl6  ANY   ANY
 [ 8] hackdetector     RUN   -    hackdetector_amx  v0.15.22  pl6  ANY   ANY
 [ 9] Orpheu           RUN   -    orpheu_amxx_i386  v2.6.3    pl6  ANY   ANY
 [10] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-d  pl6  ANY   ANY
 [11] Engine           RUN   -    engine_amxx_i386  v1.8.3-d  pl6  ANY   ANY
 [12] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-d  pl6  ANY   ANY
 [13] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl6  ANY   ANY
 [14] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-d  pl6  ANY   ANY
 [15] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-d  pl6  ANY   ANY
 [16] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-d  pl6  ANY   ANY
16 plugins, 16 running

Cvars same.

**Comment by r4sas** [comment]
Hehe, I find, why it doesn't works...
amxx modules
Currently loaded modules:
      name                    version     author               status
 [ 1] Admin Free Look         1.5.5-pre   Arkshine             newer
 [ 2] Fun                     1.8.2       AMX Mod X Dev Team   running
 [ 3] CStrike                 1.8.2       AMX Mod X Dev Team   running
 [ 4] CSX                     1.8.2       AMX Mod X Dev Team   running
 [ 5] MySQL                   1.8.2       AMX Mod X Dev Team   running
 [ 6] FakeMeta                1.8.2       AMX Mod X Dev Team   running
 [ 7] Engine                  1.8.2       AMX Mod X Dev Team   running
 [ 8] Ham Sandwich            1.8.2       AMX Mod X Dev Team   running
 [ 9] Orpheu                  2.6.3       joaquimandrade & Ar  running
 [10] RegEx                   1.8.2       AMX Mod X Dev Team   running
10 modules, 9 correct

Okay. That's mean, that error (logged to syslog) maybe was on server with AMXX 1.8.3.
With 1.5.4 works, but here problem with auto changing view point after death...
amxx modules
Currently loaded modules:
      name                    version     author               status
 [ 1] MySQL                   1.8.2       AMX Mod X Dev Team   running
 [ 2] Admin Free Look         1.5.4       Arkshine             running
 [ 3] Fun                     1.8.2       AMX Mod X Dev Team   running
 [ 4] CStrike                 1.8.2       AMX Mod X Dev Team   running
 [ 5] CSX                     1.8.2       AMX Mod X Dev Team   running
 [ 6] FakeMeta                1.8.2       AMX Mod X Dev Team   running
 [ 7] Engine                  1.8.2       AMX Mod X Dev Team   running
 [ 8] Ham Sandwich            1.8.2       AMX Mod X Dev Team   running
 [ 9] Orpheu                  2.6.3       joaquimandrade & Ar  running
 [10] RegEx                   1.8.2       AMX Mod X Dev Team   running
10 modules, 10 correct

**Comment by Arkshine** [comment]
It doesn't help really. You had others third-party metamod module too. It could be everything. Unless you're giving me a way to reproduce the crash so I can check where it crashes, it's going to be hard to figure out something.
